site_name: Tom 除錯中
dev_addr: '0.0.0.0:8116'
theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: slate
      primary: red
      accent: red
  font:
    text: Noto Sans Traditional Chinese
    code: Source Code Pro
  language: zh-TW
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - header.autohide
    - search.highlight
    - search.share
  icon:
    repo: fontawesome/brands/github
repo_url: https://github.com/tomleesm/notes
repo_name: tomleesm/notes
edit_uri: edit/main/docs/
plugins:
  - search:
      lang:
        - en
        - ja
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
extra_css:
  - stylesheets/extra.css
nav:
  - 讀書筆記:
    - HTTP 通訊協議簡介: book_notes/HTTP 通訊協議簡介.md
    - PHP 物件導向語法筆記: book_notes/PHP 物件導向語法筆記.md
    - PostgreSQL 筆記: book_notes/PostgreSQL 筆記.md
    - RESTful API 簡介: book_notes/RESTful API 簡介.md
    - 使用 API Blueprint 寫文件: book_notes/使用 API Blueprint 寫文件.md
    - 使用 Docker Compose 安裝 Laravel 和 Vue.js 環境: book_notes/使用 Docker Compose 安裝 Laravel 和 Vue.js 環境.md
    - 常用 Vim 指令清單: book_notes/常用 Vim 指令清單.md
    - Laravel 10 官方文件: book_notes/Laravel 10 官方文件.md
    - 我能讓你賺大錢: book_notes/我能讓你賺大錢.md
    - 用五個為什麼，找出問題發生的真因: book_notes/用五個為什麼，找出問題發生的真因.md
    - 讓你和孩子更貼心：現代父母效能訓練: book_notes/讓你和孩子更貼心：現代父母效能訓練.md
    - 廚房再也不麻煩: book_notes/廚房再也不麻煩.md
    - 為什麼他接的案子比我多？: book_notes/為什麼他接的案子比我多？.md
    - 數學思考: book_notes/數學思考.md
    - 拒看新聞的生活藝術: book_notes/拒看新聞的生活藝術.md
    - 做自己的生命設計師: book_notes/做自己的生命設計師.md
    - 關於寫作：一隻鳥接著一隻鳥: book_notes/關於寫作：一隻鳥接著一隻鳥.md
    - 原子習慣: book_notes/原子習慣.md
    - 刻意練習: book_notes/刻意練習.md
    - 敏捷與 Scrum 軟體開發速成: book_notes/敏捷與 Scrum 軟體開發速成.md
  - 雜記:
    - 我為什麼想不開用 Vim 寫程式？: others/我為什麼想不開用 Vim 寫程式？.md
    - 怎麽學 Vim ？: others/怎麽學 Vim ？.md
    - 資料庫正規化，以魔法學校課程為例: others/資料庫正規化，以魔法學校課程為例.md
    - Git rebase 是什麼？: others/Git rebase 是什麼？.md
    - GitHub 預設分支 master 改名為 main: others/GitHub 預設分支 master 改名為 main.md
    - Git 設定: others/Git 設定.md
    - <好書推薦>為什麼他接的案子比我多: others/<好書推薦>為什麼他接的案子比我多.md
    - 這週看了什麼書: others/這週看了什麼書.md
    - 在 Dedian 11 安裝 LEMP 開發環境跑 Laravel 10: others/在 Dedian 11 安裝 LEMP 開發環境跑 Laravel 10.md
    - 在 Dedian 12 安裝 LEMP 開發環境跑 Laravel 10: others/在 Dedian 12 安裝 LEMP 開發環境跑 Laravel 10.md
    - 列印 Laravel 10 官方文件中文版: others/列印 Laravel 10 官方文件中文版.md
    - 從 Vim 到 Neovim: others/從 Vim 到 Neovim.md
    - Netrw 簡介: others/Netrw 簡介.md
    - 為什麼要有例外處理？: others/為什麼要有例外處理？.md
    - 解 UVa 線上解題系統的題目: others/解 UVa 線上解題系統的題目.md
    - 用 Vim 把事情分得很細: others/用 Vim 把事情分得很細.md
    - 時間管理方法: others/時間管理方法.md
    - 用 Linux Mint 做為工作環境: others/用 Linux Mint 做為工作環境.md
    - Windows Terminal 設定多個字體: others/Windows Terminal 設定多個字體.md
    - 解決 VTE 為基礎的終端機程式游標問題: others/解決 VTE 為基礎的終端機程式游標問題.md
    - Windows 10 推薦軟體: others/Windows 10 推薦軟體.md
    - memos 安裝到 Debian 9: others/memos 安裝到 Debian 9.md
  - Laravel 10 語法速查表:
    - Artisan: cheatsheets/artisan.md
    - Auth 使用者認證: cheatsheets/auth.md
    - Blade 範本: cheatsheets/blade.md
    - Cache: cheatsheets/cache.md
    - Collection: cheatsheets/collection.md
    - Composer: cheatsheets/composer.md
    - Config: cheatsheets/config.md
    - Container: cheatsheets/container.md
    - Cookie: cheatsheets/cookie.md
    - Database: cheatsheets/db.md
    - Environment: cheatsheets/environment.md
    - Event: cheatsheets/event.md
    - File: cheatsheets/file.md
    - Helper: cheatsheets/helper.md
    - Input: cheatsheets/input.md
    - Lang: cheatsheets/lang.md
    - Log: cheatsheets/Log.md
    - Mail: cheatsheets/mail.md
    - Model (Eloquent ORM): cheatsheets/model.md
    - Pagination: cheatsheets/pagination.md
    - Queue: cheatsheets/queue.md
    - Redirect: cheatsheets/redirect.md
    - Request: cheatsheets/request.md
    - Response: cheatsheets/response.md
    - Route: cheatsheets/route.md
    - Schema 資料庫結構: cheatsheets/schema.md
    - Security (Hash 和加解密): cheatsheets/security.md
    - Session: cheatsheets/session.md
    - Storage: cheatsheets/storage.md
    - String: cheatsheets/string.md
    - Unit Test 單元測試: cheatsheets/unittest.md
    - URL: cheatsheets/url.md
    - Validation 表單驗證: cheatsheets/validation.md
    - View: cheatsheets/view.md
