site_name: Tom 除錯中
dev_addr: '0.0.0.0:8116'
theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: slate
      primary: red
      accent: red
  font:
    text: Noto Sans Traditional Chinese
    code: Source Code Pro
  language: zh-TW
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - header.autohide
    - search.highlight
    - search.share
  icon:
    repo: fontawesome/brands/github
repo_url: https://github.com/tomleesm/notes
repo_name: tomleesm/notes
edit_uri: edit/main/docs/
plugins:
  - search:
      lang:
        - en
        - ja
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
extra_css:
  - stylesheets/extra.css
nav:
  - Laravel 10 語法速查表:
    - Artisan: cheatsheets/artisan.md
    - Auth 使用者認證: cheatsheets/auth.md
    - Blade 範本: cheatsheets/blade.md
    - Cache: cheatsheets/cache.md
    - Collection: cheatsheets/collection.md
    - Composer: cheatsheets/composer.md
    - Config: cheatsheets/config.md
    - Container: cheatsheets/container.md
    - Cookie: cheatsheets/cookie.md
    - Database: cheatsheets/db.md
    - Environment: cheatsheets/environment.md
    - Event: cheatsheets/event.md
    - File: cheatsheets/file.md
    - Helper: cheatsheets/helper.md
    - Input: cheatsheets/input.md
    - Lang: cheatsheets/lang.md
    - Log: cheatsheets/Log.md
    - Mail: cheatsheets/mail.md
    - Model (Eloquent ORM): cheatsheets/model.md
    - Pagination: cheatsheets/pagination.md
    - Queue: cheatsheets/queue.md
    - Redirect: cheatsheets/redirect.md
    - Request: cheatsheets/request.md
    - Response: cheatsheets/response.md
    - Route: cheatsheets/route.md
    - Schema 資料庫結構: cheatsheets/schema.md
    - Security (Hash 和加解密): cheatsheets/security.md
    - Session: cheatsheets/session.md
    - Storage: cheatsheets/storage.md
    - String: cheatsheets/string.md
    - Unit Test 單元測試: cheatsheets/unittest.md
    - URL: cheatsheets/url.md
    - Validation 表單驗證: cheatsheets/validation.md
    - View: cheatsheets/view.md
