site_name: Tom 株式會社
dev_addr: '0.0.0.0:8116'
theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: slate
      primary: red
      accent: red
  font:
    text: Noto Sans Traditional Chinese
    code: Source Code Pro
  language: zh-TW
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - header.autohide
    - search.highlight
    - search.share
  icon:
    repo: fontawesome/brands/github
repo_url: https://github.com/tomleesm/notes
repo_name: tomleesm/notes
edit_uri: edit/main/docs/
plugins:
  - search:
      lang:
        - en
        - ja
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
extra_css:
  - stylesheets/extra.css
nav:
  - 筆記:
    - 我是怎麼寫程式的？: how-do-i-program.md
    - RESTful API 簡介: restful-api-introduction.md
    - 使用 API Blueprint 寫文件: api-blueprint.md
    - 使用 Swagger 寫文件: swagger.md
    - 使用 Cypress 測試網站: cypress.md
    - PostgreSQL 懶人包: postgresql-cheat-sheet.md
    - 資料庫正規化: database-normalization.md
    - Docker 懶人包: docker-cheat-sheet.md
    - HTTP 通訊協議簡介: http-protocol-introduction.md
    - PHP 物件導向語法: php-oop.md
    - Laravel RESTful controller 範例: laravel-docs/restful-controller-example.md
  - Laravel 官方文件懶人包:
    - 基礎:
      - 路由: laravel-docs/basic/routes.md
      - CSRF 保護: laravel-docs/basic/csrf-protection.md
      - Controllers: laravel-docs/basic/controllers.md
      - CSRF 保護: laravel-docs/basic/csrf-protection.md
      - HTTP 請求: laravel-docs/basic/request.md
      - HTTP 回應: laravel-docs/basic/response.md
      - View: laravel-docs/basic/view.md
      - Signed URLs: laravel-docs/basic/signed-urls.md
      - Cookie 和 Session: laravel-docs/basic/cookie-session.md
      - 表單驗證: laravel-docs/basic/form-validation.md
      - 驗證規則清單: laravel-docs/basic/form-validation-rules.md
      - 例外處理: laravel-docs/basic/exception-handling.md
      - Log: laravel-docs/basic/log.md
      - 檔案上傳和下載: laravel-docs/basic/file-upload-download.md
    - 前端:
      - Blade: laravel/front-end/blade.md
