site_name: Tom's Notes
dev_addr: '0.0.0.0:8116'
theme:
  name: material
  palette:
    - scheme: slate
      primary: red
      accent: red
  font:
    text: Noto Sans Traditional Chinese
    code: Source Code Pro
  language: zh-TW
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - header.autohide
  icon:
    repo: fontawesome/brands/github
repo_url: https://github.com/tomleesm/notes
repo_name: tomleesm/notes
edit_uri: edit/main/docs/
plugins:
  - git-revision-date
markdown_extensions:
  - pymdownx.superfences:
extra_css:
  - stylesheets/extra.css
nav:
  - 筆記:
    - 我是怎麼寫程式的？: how-do-i-program.md
