site_name: Tom 株式會社
dev_addr: '0.0.0.0:8116'
theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: slate
      primary: red
      accent: red
  font:
    text: Noto Sans Traditional Chinese
    code: Source Code Pro
  language: zh-TW
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - header.autohide
    - search.highlight
    - search.share
  icon:
    repo: fontawesome/brands/github
repo_url: https://github.com/tomleesm/notes
repo_name: tomleesm/notes
edit_uri: edit/main/docs/
plugins:
  - search:
      lang:
        - en
        - ja
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
extra_css:
  - stylesheets/extra.css
nav:
  - 核心架構:
    - 請求的生命週期: 01核心架構/01請求的生命週期.md
    - 服務容器: 01核心架構/02服務容器.md
    - 服務提供者: 01核心架構/03服務提供者.md
    - Facades: 01核心架構/04Facades.md
  - 基礎功能:
    - 路由: 02基礎功能/01路由.md
    - 中介軟體: 02基礎功能/02中介軟體.md
    - CSRF 保護: 02基礎功能/03CSRF保護.md
    - Controller: 02基礎功能/04Controller.md
    - HTTP 請求: 02基礎功能/05HTTP請求.md
    - HTTP 響應: 02基礎功能/06HTTP響應.md
    - 檢視: 02基礎功能/07檢視.md
    - Blade 範本: 02基礎功能/08Blade範本.md
    - Vite 編譯 Assets: 02基礎功能/09Vite編譯Assets.md
    - 生成 URL: 02基礎功能/10生成URL.md
    - Session: 02基礎功能/11Session.md
    - 表單驗證: 02基礎功能/12表單驗證.md
    - 錯誤處理: 02基礎功能/13錯誤處理.md
    - 日誌: 02基礎功能/14日誌.md
  - 繼續深入:
    - Artisan 命令列: 03繼續深入/01Artisan命令列.md
    - 廣播: 03繼續深入/02廣播.md
    - 快取系統: 03繼續深入/03快取系統.md
    - 集合: 03繼續深入/04集合.md
    - 契約 Contract: 03繼續深入/05契約Contract.md
    - 事件系統: 03繼續深入/06事件系統.md
    - 檔案儲存: 03繼續深入/07檔案儲存.md
    - HTTP Client: 03繼續深入/09HTTPClient.md
    - 本地化: 03繼續深入/10本地化.md
    - 郵件: 03繼續深入/11郵件.md
    - 消息通知: 03繼續深入/12消息通知.md
    - Package 開發: 03繼續深入/13Package開發.md
    - 處理程序管理: 03繼續深入/14處理程序管理.md
    - 佇列: 03繼續深入/15佇列.md
    - 限流: 03繼續深入/16限流.md
    - 任務調度: 03繼續深入/17任務調度.md
  - 安全相關:
    - 使用者認證: 04安全相關/01使用者認證.md
    - 使用者授權: 04安全相關/02使用者授權.md
    - Email 認證: 04安全相關/03Email認證.md
    - 加密解密: 04安全相關/04加密解密.md
    - 雜湊: 04安全相關/05雜湊.md
    - 重設密碼: 04安全相關/06重設密碼.md
  - 資料庫:
    - 快速入門: 05資料庫/01快速入門.md
    - 查詢生成器: 05資料庫/02查詢生成器.md
    - 分頁: 05資料庫/03分頁.md
    - 遷移: 05資料庫/04遷移.md
    - 資料填充: 05資料庫/05資料填充.md
    - Redis: 05資料庫/06Redis.md
  - Eloquent ORM:
    - 快速入門: 06EloquentORM/01快速入門.md
    - 關聯: 06EloquentORM/02關聯.md
    - 集合: 06EloquentORM/03集合.md
    - 屬性修改器: 06EloquentORM/04屬性修改器.md
    - API 資源: 06EloquentORM/05API資源.md
    - 序列化: 06EloquentORM/06序列化.md
    - 資料工廠: 06EloquentORM/07資料工廠.md
  - 測試相關:
    - 入門: 07測試相關/01入門.md
    - HTTP 測試: 07測試相關/02HTTP測試.md
    - 命令列測試: 07測試相關/03命令列測試.md
    - Laravel Dusk: 07測試相關/04LaravelDusk.md
    - 資料庫測試: 07測試相關/05資料庫測試.md
    - Mocking: 07測試相關/06Mocking.md
  - 官方擴展包:
    - Cashier 交易工具包 Stripe: 08官方擴展包/01Cashier交易工具包Stripe.md
    - Cashier 交易工具包 Paddle: 08官方擴展包/02Cashier交易工具包Paddle.md
    - Envoy 部署工具: 08官方擴展包/03Envoy部署工具.md
    - Fortify 與前端無關的身份認證後端實現: 08官方擴展包/04Fortify與前端無關的身份認證後端實現.md
    - Homestead 虛擬機器: 08官方擴展包/05Homestead虛擬機器.md
    - Horizon 佇列管理工具: 08官方擴展包/06Horizon佇列管理工具.md
    - Octane 加速引擎: 08官方擴展包/09Octane加速引擎.md
    - Passport OAuth 認證: 08官方擴展包/10PassportOAuth認證.md
    - Pennant 測試新功能: 08官方擴展包/11Pennant測試新功能.md
    - Pint 程式碼風格: 08官方擴展包/12Pint程式碼風格.md
    - Sail Docker 開發環境: 08官方擴展包/13SailDocker開發環境.md
    - Sanctum API 授權: 08官方擴展包/14SanctumAPI授權.md
    - Scout 全文搜尋: 08官方擴展包/15Scout全文搜尋.md
    - Socialite 第三方登入: 08官方擴展包/16Socialite第三方登入.md
    - Telescope 偵錯工具: 08官方擴展包/17Telescope偵錯工具.md
